baseURL: 'https://comunidadamanecer.netlify.app/'
languageCode: es-cr
title: Comunidad Amancer
theme: alpha-church
rssLimit: 5
paginate: 4
enableEmoji: true
googleAnalytics: ''
enableInlineShortcodes: true
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  tag: tags
  preacher: preachers
  series: series
menu:
  main:
    - name: Amanecer
      url: /
      weight: 1
    - name: Comunidad
      url: /comunidad
      weight: 2
    - name: Recursos
      url: '#'
      weight: 3
    - name: Podcasts
      url: /podcasts
      parent: Recursos
      weight: 1
    - name: Cursos
      url: /cursos
      parent: Recursos
      weight: 2
    - name: Blog
      url: /posts
      weight: 4
    - name: Contacto
      url: /contacto
      weight: 5
params:
  title: Comunidad Amanecer
  subtitle: Dios brilla para todos
  # author: Daniel Saunders
  keywords:
    - theme
    - hugo
    - podcast
  languageCode: es
  bible_popups: blb
  bible_version: RVR60
  instant_page: true
  # customCSS:
  #   - example.css
  # favicon:
  #   sml: /example16.png
  #   med: /example32.png
  banner:
    image: img/freely-68918.jpg
  podcast:
    title: Podcasts de Comunidad Amanecer
    summary: 'Enseñanzas, series, estudios'
    email: test@example.com
    copyright: © 2022 Comunidad Amanecer
    image: img/podcast-cover.jpg
    category: Religion & Spirituality
    sub_category: Cristianismo
    # iTunes: 'https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280'
    feed: >-
      https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast
    spotify: 'https://open.spotify.com/show/1iE3aJkf8fJ2FVTvJGFd4h'
  map:
    service: osm
    latitude: '9.93221'
    longitude: '-84.13235'
    zoom: '18'
  contact:
    service: netlify
    confirm_page: /contact_thanks
  footer:
    copyright:
      - '© 2022 Comunidad Amanecer'
      - '[Alpha Church Theme](//github.com/funkydan2/alpha-church) by [Daniel Saunders](//github.com/funkydan2)'
  links:
    - service: Facebook
      icon: fa-facebook
      icon_pack: fab
      link: //facebook.com/
    - service: Podcast
      icon: fa-podcast
      icon_pack: fas
      link: /podcasts/index.xml
    - service: Full RSS Feed
      icon: fa-rss
      icon_pack: fas
      link: /index.xml
