baseURL: 'https://comunidadamanecer.com/'
languageCode: es
defaultContentLanguage: es
title: Comunidad Amancer
theme: alpha-church
rssLimit: 5
paginate: 5
enableEmoji: true
googleAnalytics: 'G-S4Y9RZBMQ7'
enableInlineShortcodes: true
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  tag: tags
  preacher: preachers
  series: series
# languages:
#   es:
#     disabled: false
#     languageCode: es
#     languageName: "Español"
#     weight: 0
#   en:
#     disabled: true
#     languageCode: en
#     languageName: "English"
#     weight: 1
menu:
  main:
    - name: Inicio
      url: /
      weight: 1
    # - name: Comunidad
    #   url: /comunidad
    #   weight: 2
    # - name: Recursos
    #   url: '#'
    #   weight: 3
    # - name: Podcasts
    #   url: /podcasts
    #   parent: Recursos
    #   weight: 1
    # - name: Cursos
    #   url: /cursos
    #   parent: Recursos
    #   weight: 2
    # - name: Blog
    #   url: /posts
    #   weight: 4
    - name: Cursos
      url: https://gracia.krestomatio.site
      weight: 5
    - name: Contacto
      url: /contacto
      weight: 6
params:
  title: Comunidad Cristiana Amanecer
  subtitle: Dios brilla para todos
  # author: Daniel Saunders
  keywords:
    - theme
    - hugo
    - podcast
  languageCode: es
  bible_popups: blb
  bible_version: NIV
  instant_page: true
  customCSS:
    - css/custom.css
  favicon:
    sml: /img/icon_Color_1.ico
    med: /img/icon_Color_1.ico
    lge: /img/icon_Color_1.ico
  banner:
    image: /img/freely-68918.jpg
  # podcast:
  #   title: Podcasts de Comunidad Amanecer
  #   summary: 'Enseñanzas, series, estudios'
  #   email: info@comunidadamanecer.com
  #   copyright: © 2023 Comunidad Amanecer
  #   image: /img/podcast-cover.jpg
  #   category: Religión y espiritualidad
  #   sub_category: Cristianismo
  #   # iTunes: 'https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280'
  #   feed: >-
  #     https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast
  #   spotify: 'https://open.spotify.com/show/1iE3aJkf8fJ2FVTvJGFd4h'
  map:
    service: osm
    latitude: '9.93221'
    longitude: '-84.13235'
    zoom: '18'
  contact:
    service: netlify
    confirm_page: /contact_thanks
  footer:
    copyright:
      - '© 2023 Comunidad Amanecer'
      - '[Alpha Church Theme](//github.com/funkydan2/alpha-church) by [Daniel Saunders](//github.com/funkydan2)'
  links:
    - service: Youtube
      icon: fa-youtube
      icon_pack: fab
      link: //youtube.com/@comunidadamanecer
    - service: WhatsApp
      icon: fa-whatsapp
      icon_pack: fab
      link: //wa.link/comunidadamanecer
    - service: Facebook
      icon: fa-facebook
      icon_pack: fab
      link: //facebook.com/ComunidadCristianaAmanecer
    # - service: Podcast
    #   icon: fa-podcast
    #   icon_pack: fas
    #   link: /podcasts/index.xml
    # - service: Full RSS Feed
    #   icon: fa-rss
    #   icon_pack: fas
    #   link: /index.xml
